name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build (stable)
      run: cargo build --verbose
    - name: Test (stable)
      run: cargo test --verbose
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build nightly
      run: cargo build --verbose
    - name: Test nightly
      run: cargo test --verbose
